# fly.toml app configuration file generated for discord-word-bot-green-water-4664 on 2026-01-08T02:16:38+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discord-word-bot'
primary_region = 'fra'

[build]
  builder = 'paketobuildpacks/builder:base'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
